---
# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Chris-Prime/FactionsPE
model: default
branches:
- reborn
projects:
  FactionsPE:
    path: ""
    model: default
    libs: []
    icon: fpe-logo.png
...
